### PR TITLE
Enhancement/proptype validation responsive modifiers size

### LINKED ISSUE #27: Enhance proptypes validation for responsive modifiers
## PROPOSED BEHAVIOR
If a modifier prop is used that is responsive (it is an object) but no size prop is provided, the proptypes validators should throw an error advising the developer to add the size prop. This is different than if the size prop doesn't match a key (which maybe shouldn't throw an error).

## CURRENT BEHAVIOR
Currently this throws no errors, and when a developer encounters this they just get no modifiers applied.

## STEPS TO REPRODUCE
_Please provide some simple steps to reproduce the issue._
* Create a component with modifiers.
* Render the component in an application using an object syntax to declare the modifiers.
* Do not provide a `size` prop
* Observe no errors and no styles applied.

## SUGGESTED SOLUTION
* This could (and probably should) be done as an enhancement to the proptypes logic. Basically a `size` prop is required if the modifiers prop is a responsive format.

### PR DESCRIPTION
**Pull request by Nauthiz-Jera**
## OVERVIEW

PR based on this open Issue:
closes https://github.com/Decisiv/styled-components-modifiers/issues/27

## WHERE SHOULD THE REVIEWER START?

`src/styleModifierPropTypes.ts`
`src/responsiveStyleModifierPropTypes.ts`

## HOW CAN THIS BE MANUALLY TESTED?

- Create a component with modifiers.
- Render the component in an application using an object syntax to declare the modifiers.
- Do not provide a size prop
- Observe no errors and no styles applied.

## ANY NEW DEPENDENCIES ADDED?

No new dependencies

## CHECKLIST

_Be sure all items are_ ✅ _before submitting a PR for review._

- [x] Verify the linter and tests pass: `npm run review`
- [x] Verify this branch is rebased with the latest master

## GIF

_Share a fun GIF to say thanks to your reviewer:_ https://giphy.com

### CODE REVIEW

File: src/styleModifierPropTypes.ts [hunk 1]
```diff
@@ -88,17 +88,25 @@ function validateModifiers(
...
 export function validateResponsiveModifiers(
   modifiersPropName: string,
   componentName: string,
   responsiveModifiers: ResponsiveModifiersProp<ModifiersConfig, {}>,
   modifierConfig: ModifiersConfig,
+  sizeProp: string,
 ): Error | null {
   const rawInvalidModifiers: string[][] = [];
   const rawSizesWithErrors: string[] = [];
+  // eslint-disable-next-line
```
Comment (andrewtpoe) [inline src/styleModifierPropTypes.ts]: This isn't needed.

File: src/styleModifierPropTypes.ts [hunk 2]
```diff
@@ -88,17 +88,25 @@ function validateModifiers(
...
 
+  if (!sizeProp) {
+    return new Error(
+      'Invalid Responsive Modifier; size prop must be included when using Responsive Modifiers.',
+    );
+  }
```
Comment (andrewtpoe) [inline src/styleModifierPropTypes.ts:108]: Please add a new empty line after this code block.

File: src/styleModifierPropTypes.ts [hunk 3]
```diff
@@ -144,13 +152,15 @@ export default function styleModifierPropTypes(
     componentName: string,
   ): Error | null => {
     const modifiers = props[modifiersPropName];
+    const sizeProp = props.size;
```
Comment (andrewtpoe) [inline src/styleModifierPropTypes.ts]: This will work if the size prop is any truthy value, but it is also possible that the size may actually be `undefined`.  Maybe a better check would be `props.hasOwnProperty('size')`. We really only care that the size prop is declared, not what its value is. Please add a test case for this scenario as well.

File: src/styleModifierPropTypes.ts [hunk 4]
```diff
@@ -88,17 +88,25 @@ function validateModifiers(
...
   modifierConfig: ModifiersConfig,
+  sizeProp: string,
 ): Error | null {
   const rawInvalidModifiers: string[][] = [];
   const rawSizesWithErrors: string[] = [];
+  // eslint-disable-next-line
 
+  if (!sizeProp) {
+    return new Error(
+      'Invalid Responsive Modifier; size prop must be included when using Responsive Modifiers.',
```
Comment (andrewtpoe) [inline src/styleModifierPropTypes.ts]: I think I'd like to change the wording on this error message a bit to be more in line with the other error messages generated for proptype failures. Maybe:

`Invalid responsive prop supplied to <ComponentName>. Prop 'size' must be included when using responsive modifiers. Validation failed.`

File: src/__tests__/styleModifierPropTypes.js [hunk 5]
```diff
@@ -162,3 +165,27 @@ test('styleModifierPropTypes logs error with invalid modifier keys when responsi
   consoleSpy.mockReset();
   consoleSpy.mockRestore();
 });
+
+test('styleModifierPropTypes logs error when no size prop is passed when using responsive modifiers', () => {
```
Comment (andrewtpoe) [inline src/__tests__/styleModifierPropTypes.js:169]: 💯

**Review by andrewtpoe — CHANGES_REQUESTED** [review]
This is great work, thank you for contributing!

I've left just a few comments I'd like to see get resolved before this gets merged.

**Comment by Nauthiz-Jera** [comment]
Thanks! Glad to help, I've made the changes per-requested. If there is any other changes you'd like please let me know.

**Comment by andrewtpoe** [comment]
This code is ready to merge, but doing so will cause a breaking change. Code that was previously ok will now throw PropTypes errors and may break.

This is going to be targeted at v2. The rest of v2 is still being planned, so we are going to sit on this for a little while.

**Comment by andrewtpoe** [comment]
I've got a v2 feature set planned out in the issues. I'm going to re-target this at that branch and merge it in now. Thanks again for your contributions!

**Review by andrewtpoe — APPROVED** [review]
